openapi: 3.0.0
info:
  title: Ping API
  description: Sample Ping API.
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Local testing environment  
paths:
  /rest/v1/ping:
    get:
      summary: Simple ping.
      tags:
        - ping
      security:
        - OAuth2:
          - read
      responses:
        '200':
          description: Sample pong response
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Pong"
    post:
      summary: Ping with an optional token.
      tags:
        - ping
      security:
        - OAuth2:
          - write
      parameters:
          - name: token
            in: query
            required: false
            description: Token provided by the ping caller
            schema:
                type: string
                example: pong
      responses:
        '200':
          description: Sample pong response
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Pong"
        '400':
          description: Validation error

  /rest/v1/pingbody:
    post:
      summary: Ping with JSON body in request
      tags:
        - ping
      security:
        - OAuth2:
          - write
      requestBody:
        description: Sample ping request
        content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Ping"
      responses:
        '200':
          description: Sample pong response
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Pong"
        '400':
          description: Validation error

components:
  schemas:
    Ping:
      type: object
      properties:
        token:
          type: string
          example: "ping"
          description: "Ping token"
    Pong:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2000-01-01T00:00:00.000+00:00"
          description: "Current timestamp"
        token:
          type: string
          example: "pong"
          description: "Ping token"
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://localhost:8070/oauth2/token
          scopes:
            read: Grant read-only access to the data
            write: Grant write access to the data
